"""
 +----------------------------------+
 | Supreme Machines/Jetpack         |
 | Flatcat simple CSL experiment    |
 | Build Script                     |
 | Matthias Kubisch                 |
 | kubisch@informatik.hu-berlin.de  |
 | Oct 2020                         |
 +----------------------------------+

"""
Import('env')

src_files = [ 'ux0_serial.cpp' ]

# common flags
cppflags = ['-O2', '-Wall', '-Wextra', '-Wno-psabi', '-Wfatal-errors']

# c++ only flags
cxxflags = ['-std=c++11']

cpppaths = [ '.'
           , '../../framework/src/'
           , '../../simloidTCP/src/'
           , '../../libsensorimotor/src/'
           , '../src/'
           , '../src/system/'
           ]

# compile time for version number
from datetime import datetime
dt = datetime.now()
version = dt.strftime("%Y-%m-%d %H:%M:%S")

env.Append(CPPDEFINES=[ '__COMPILETIMESTAMP__={}'.format(version)])

env.Program( '../ux0_serial'
           , LIBS=['framework', 'pthread', 'stdc++fs']
           , LIBPATH = ["../../framework"]
           , source = src_files
           , CPPPATH = cpppaths
           , CPPFLAGS = cppflags
           , CXXFLAGS = cxxflags
           )
