"""
 +----------------------------------+
 | Supreme Machines/Jetpack         |
 | Flatcat simple CSL experiment    |
 | Build Script                     |
 | Matthias Kubisch                 |
 | kubisch@informatik.hu-berlin.de  |
 | Oct 2020                         |
 +----------------------------------+

"""

src_files = [ 'ux0_serial.cpp' ]

# common flags
cppflags = ['-O2', '-Wall', '-Wextra', '-Wno-psabi']

# c++ only flags
cxxflags = ['-std=c++11']

#Library('foo', ['f1.c', 'f2.c', 'f3.c'])

cpppaths = [ '.'
           , '../../framework/src/'
           , '../../simloidTCP/src/'
           , '../../libsensorimotor/src/'
           , '../src/'
           ]


Program('../ux0_serial', LIBS=['framework', 'pthread'], LIBPATH = ["../../framework"], source = src_files, CPPPATH=cpppaths, CPPFLAGS=cppflags, CXXFLAGS=cxxflags)
